# coding: utf-8

"""
    Service Fabric Reliable Collection Backup Explorer OpenApi

    OpenApi spec of [service-fabric-backup-explorer](http://github.com/Microsoft/service-fabric-backup-explorer).  # noqa: E501

    OpenAPI spec version: 0.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AddTransactionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'str',
        'collection': 'str',
        'partition_id': 'str',
        'key': 'object',
        'value': 'object',
        'etag': 'str'
    }

    attribute_map = {
        'operation': 'Operation',
        'collection': 'Collection',
        'partition_id': 'PartitionId',
        'key': 'Key',
        'value': 'Value',
        'etag': 'Etag'
    }

    def __init__(self, operation=None, collection=None, partition_id=None, key=None, value=None, etag=None):  # noqa: E501
        """AddTransactionRequest - a model defined in Swagger"""  # noqa: E501
        self._operation = None
        self._collection = None
        self._partition_id = None
        self._key = None
        self._value = None
        self._etag = None
        self.discriminator = None
        if operation is not None:
            self.operation = operation
        if collection is not None:
            self.collection = collection
        if partition_id is not None:
            self.partition_id = partition_id
        if key is not None:
            self.key = key
        if value is not None:
            self.value = value
        if etag is not None:
            self.etag = etag

    @property
    def operation(self):
        """Gets the operation of this AddTransactionRequest.  # noqa: E501

        Operation of the perfomred transaction  # noqa: E501

        :return: The operation of this AddTransactionRequest.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this AddTransactionRequest.

        Operation of the perfomred transaction  # noqa: E501

        :param operation: The operation of this AddTransactionRequest.  # noqa: E501
        :type: str
        """

        self._operation = operation

    @property
    def collection(self):
        """Gets the collection of this AddTransactionRequest.  # noqa: E501

        Changed dictionary name  # noqa: E501

        :return: The collection of this AddTransactionRequest.  # noqa: E501
        :rtype: str
        """
        return self._collection

    @collection.setter
    def collection(self, collection):
        """Sets the collection of this AddTransactionRequest.

        Changed dictionary name  # noqa: E501

        :param collection: The collection of this AddTransactionRequest.  # noqa: E501
        :type: str
        """

        self._collection = collection

    @property
    def partition_id(self):
        """Gets the partition_id of this AddTransactionRequest.  # noqa: E501

        Partition id   # noqa: E501

        :return: The partition_id of this AddTransactionRequest.  # noqa: E501
        :rtype: str
        """
        return self._partition_id

    @partition_id.setter
    def partition_id(self, partition_id):
        """Sets the partition_id of this AddTransactionRequest.

        Partition id   # noqa: E501

        :param partition_id: The partition_id of this AddTransactionRequest.  # noqa: E501
        :type: str
        """

        self._partition_id = partition_id

    @property
    def key(self):
        """Gets the key of this AddTransactionRequest.  # noqa: E501

        Key of the dictionary  # noqa: E501

        :return: The key of this AddTransactionRequest.  # noqa: E501
        :rtype: object
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this AddTransactionRequest.

        Key of the dictionary  # noqa: E501

        :param key: The key of this AddTransactionRequest.  # noqa: E501
        :type: object
        """

        self._key = key

    @property
    def value(self):
        """Gets the value of this AddTransactionRequest.  # noqa: E501

        value of the update  # noqa: E501

        :return: The value of this AddTransactionRequest.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this AddTransactionRequest.

        value of the update  # noqa: E501

        :param value: The value of this AddTransactionRequest.  # noqa: E501
        :type: object
        """

        self._value = value

    @property
    def etag(self):
        """Gets the etag of this AddTransactionRequest.  # noqa: E501

        Details of the request  # noqa: E501

        :return: The etag of this AddTransactionRequest.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this AddTransactionRequest.

        Details of the request  # noqa: E501

        :param etag: The etag of this AddTransactionRequest.  # noqa: E501
        :type: str
        """

        self._etag = etag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddTransactionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddTransactionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
